name: "Deploy"

on: push 

permissions:
  contents: write
  packages: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: "☁️ checkout repository"
        uses: actions/checkout@v4

      - name: "🚧️ setup node"
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'npm'

      - name: "📦 install dependencies"
        run: npm ci

      - name: "📦 build static"
        run: npm run build

      - name: "🚀 deploy static"
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
          commit_message: ${{ github.event.head_commit.message }}
          enable_jekyll: false
          cname: training.morganambrose.work